# Generated by Django 6.0.3 on 2026-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mobilia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("MESA", "Mesa"),
                            ("CADEIRA", "Cadeira"),
                            ("ARMARIO", "Armário"),
                            ("ESTANTE", "Estante"),
                            ("SOFA", "Sofá"),
                            ("BELICHE", "Beliche"),
                            ("GUARDA", "Guarda-volumes"),
                            ("BANQUETA", "Banqueta"),
                            ("BALCAO", "Balcão"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(max_length=200, verbose_name="Descrição"),
                ),
                (
                    "material",
                    models.CharField(
                        choices=[
                            ("MADEIRA", "Madeira"),
                            ("METAL", "Metal"),
                            ("PLASTICO", "Plástico"),
                            ("VIDRO", "Vidro"),
                            ("MISTO", "Misto"),
                        ],
                        max_length=20,
                        verbose_name="Material",
                    ),
                ),
                (
                    "patrimonio",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Nº Patrimônio",
                    ),
                ),
                (
                    "dimensoes",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 1.50x0.80x0.75",
                        max_length=50,
                        verbose_name="Dimensões (LxPxA)",
                    ),
                ),
                (
                    "cor",
                    models.CharField(blank=True, max_length=50, verbose_name="Cor"),
                ),
                (
                    "localizacao",
                    models.CharField(
                        max_length=100, verbose_name="Localização (Sala/Setor)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em Uso"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("BAIXADO", "Baixado"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "estado_conservacao",
                    models.TextField(blank=True, verbose_name="Estado de Conservação"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Mobília",
                "verbose_name_plural": "Mobílias",
                "ordering": ["tipo", "descricao"],
            },
        ),
    ]
