# Generated by Django 6.0.3 on 2026-03-07 18:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovimentacaoMunicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada (Compra/Doação)"),
                            ("SAIDA_CAUTELA", "Saída por Cautela"),
                            ("DEVOLUCAO_CAUTELA", "Devolução de Cautela"),
                            ("AJUSTE", "Ajuste de Estoque"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "data_movimentacao",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Data"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
            ],
            options={
                "verbose_name": "Movimentação",
                "verbose_name_plural": "Movimentações",
                "ordering": ["-data_movimentacao"],
            },
        ),
        migrations.CreateModel(
            name="Municao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calibre", models.CharField(max_length=20, verbose_name="Calibre")),
                (
                    "fabricante",
                    models.CharField(max_length=100, verbose_name="Fabricante"),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "quantidade",
                    models.IntegerField(
                        default=0, verbose_name="Quantidade em Estoque"
                    ),
                ),
                (
                    "quantidade_minima",
                    models.IntegerField(default=10, verbose_name="Quantidade Mínima"),
                ),
                ("validade", models.DateField(verbose_name="Data de Validade")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Munição",
                "verbose_name_plural": "Munições",
                "ordering": ["calibre", "fabricante", "modelo"],
            },
        ),
    ]
