# Generated by Django 6.0.3 on 2026-03-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro_municoes", "0001_initial"),
        ("cautela_armamento", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacaomunicao",
            name="cautela",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes_municao",
                to="cautela_armamento.cautela",
            ),
        ),
        migrations.AddField(
            model_name="movimentacaomunicao",
            name="criado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="municao",
            unique_together={("calibre", "fabricante", "modelo", "validade")},
        ),
        migrations.AddField(
            model_name="movimentacaomunicao",
            name="municao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimentacoes",
                to="cadastro_municoes.municao",
            ),
        ),
    ]
