# Generated by Django 5.2.3 on 2026-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_municoes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaomunicao",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="municao",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
