# Generated by Django 6.0.3 on 2026-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_municoes", "0003_alter_movimentacaomunicao_id_alter_municao_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimentacaomunicao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="municao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
