# Generated by Django 5.2.13 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_municoes', '0005_alter_movimentacaomunicao_id_alter_municao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacaomunicao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='municao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
