# Generated by Django 6.0.3 on 2026-03-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Viatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefixo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Prefixo"
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=8, unique=True, verbose_name="Placa"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PICKUP", "Pickup"),
                            ("SUV", "SUV"),
                            ("SEDAN", "Sedan"),
                            ("MOTO", "Motocicleta"),
                            ("CAMINHAO", "Caminhão"),
                            ("ONIBUS", "Ônibus"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                ("ano", models.IntegerField(verbose_name="Ano")),
                ("cor", models.CharField(max_length=30, verbose_name="Cor")),
                (
                    "renavam",
                    models.CharField(blank=True, max_length=20, verbose_name="Renavam"),
                ),
                (
                    "chassi",
                    models.CharField(blank=True, max_length=30, verbose_name="Chassi"),
                ),
                (
                    "km_atual",
                    models.IntegerField(default=0, verbose_name="Quilometragem Atual"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em Uso"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("BAIXADA", "Baixada"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Viatura",
                "verbose_name_plural": "Viaturas",
                "ordering": ["prefixo"],
            },
        ),
    ]
