# Generated by Django 5.2.13 on 2026-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fabricação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
    ]
