# Generated by Django 6.0.3 on 2026-03-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livro_de_cautela", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="relatorio",
            table="livro_de_cautela_relatorio",
        ),
    ]
