# Generated by Django 6.0.3 on 2026-03-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_policiais", "0003_policial_user"),
        ("livro_de_cautela", "0002_criar_modelo_relatorio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatorio",
            options={"ordering": ["-data_criacao"]},
        ),
        migrations.AddField(
            model_name="relatorio",
            name="observacoes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relatorio",
            name="policial",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cadastro_policiais.policial",
            ),
        ),
    ]
