# Generated by Django 6.0.3 on 2026-03-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "livro_de_cautela",
            "0003_alter_relatorio_options_relatorio_observacoes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="relatorio",
            name="tipo_alteracao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("COM ALTERAÇÃO", "Com Alteração"),
                    ("SEM ALTERAÇÃO", "Sem Alteração"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
