# Generated by Django 6.0.3 on 2026-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro_de_cautela', '0004_relatorio_tipo_alteracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='assinado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assinado em'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='assinatura_passou',
            field=models.ImageField(blank=True, null=True, upload_to='relatorios/assinaturas/', verbose_name='Assinatura Quem Passou'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='assinatura_recebeu',
            field=models.ImageField(blank=True, null=True, upload_to='relatorios/assinaturas/', verbose_name='Assinatura Quem Recebeu'),
        ),
    ]
