# Generated by Django 5.2.3 on 2026-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "livro_de_cautela",
            "0005_relatorio_assinado_em_relatorio_assinatura_passou_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
