# Generated by Django 6.0.3 on 2026-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("livro_de_cautela", "0006_alter_relatorio_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relatorio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
