# Generated by Django 5.2.13 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro_de_cautela', '0008_alter_relatorio_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
