# Generated by Django 6.0.4 on 2026-04-12 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VeiculoApreendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('ano', models.IntegerField()),
                ('data_apreensao', models.DateField()),
                ('local_apreensao', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('km_atual_apreensao', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quilometragem na Apreensão')),
                ('nivel_combustivel', models.CharField(blank=True, choices=[('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('CHEIO', 'Cheio'), ('RESERVA', 'Reserva')], default='1/2', max_length=20, verbose_name='Nível de Combustível')),
                ('estepe_presente', models.BooleanField(default=True, verbose_name='Estepe presente')),
                ('macaco_presente', models.BooleanField(default=True, verbose_name='Macaco presente')),
                ('chave_roda_presente', models.BooleanField(default=True, verbose_name='Chave de roda presente')),
                ('triangulo_presente', models.BooleanField(default=True, verbose_name='Triângulo de sinalização presente')),
                ('cinto_seguranca_funcionando', models.BooleanField(default=True, verbose_name='Cintos de segurança funcionando')),
                ('condicao_pneus', models.CharField(blank=True, choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], default='BOM', max_length=20, verbose_name='Condição dos pneus')),
                ('condicao_vidros', models.CharField(blank=True, choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], default='BOM', max_length=20, verbose_name='Condição dos vidros')),
                ('condicao_lataria', models.CharField(blank=True, choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], default='BOM', max_length=20, verbose_name='Condição da lataria')),
                ('condicao_motor', models.CharField(blank=True, choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], default='BOM', max_length=20, verbose_name='Condição do motor')),
                ('condicao_interna', models.CharField(blank=True, choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('RUIM', 'Ruim'), ('PESSIMO', 'Péssimo')], default='BOM', max_length=20, verbose_name='Condição interna')),
                ('radio_funcionando', models.BooleanField(default=True, verbose_name='Rádio funcionando')),
                ('ar_condicionado_funcionando', models.BooleanField(default=True, verbose_name='Ar condicionado funcionando')),
                ('direcao_funcionando', models.BooleanField(default=True, verbose_name='Direção funcionando')),
                ('trava_eletrica_funcionando', models.BooleanField(default=True, verbose_name='Trava elétrica funcionando')),
                ('vidro_eletrico_funcionando', models.BooleanField(default=True, verbose_name='Vidro elétrico funcionando')),
                ('crlv_apresentado', models.BooleanField(default=False, verbose_name='CRLV apresentado')),
                ('crv_apresentado', models.BooleanField(default=False, verbose_name='CRV apresentado')),
                ('cnh_condutor', models.CharField(blank=True, max_length=20, verbose_name='CNH do condutor')),
                ('condutor_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do condutor')),
                ('condutor_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF do condutor')),
                ('condutor_rg', models.CharField(blank=True, max_length=20, verbose_name='RG do condutor')),
                ('condutor_endereco', models.TextField(blank=True, verbose_name='Endereço do condutor')),
                ('testemunha_nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da testemunha')),
                ('testemunha_cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF da testemunha')),
                ('avarias_descricao', models.TextField(blank=True, verbose_name='Descrição detalhada de avarias')),
                ('devolvido', models.BooleanField(default=False)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevolucaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietario_nome', models.CharField(max_length=200, verbose_name='Nome do Proprietário')),
                ('proprietario_cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('proprietario_rg', models.CharField(max_length=20, verbose_name='RG')),
                ('proprietario_endereco', models.TextField(verbose_name='Endereço Completo')),
                ('proprietario_telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('proprietario_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('data_devolucao', models.DateField(auto_now_add=True, verbose_name='Data da Devolução')),
                ('hora_devolucao', models.TimeField(auto_now_add=True, verbose_name='Hora da Devolução')),
                ('estado_veiculo', models.CharField(choices=[('OTIMO', 'Ótimo'), ('BOM', 'Bom'), ('REGULAR', 'Regular'), ('DANIFICADO', 'Danificado'), ('AVARIADO', 'Avariado')], max_length=20, verbose_name='Estado do Veículo')),
                ('observacoes_veiculo', models.TextField(blank=True, verbose_name='Observações sobre o veículo')),
                ('km_atual', models.IntegerField(blank=True, null=True, verbose_name='Quilometragem Atual')),
                ('nivel_combustivel_devolucao', models.CharField(blank=True, max_length=20, verbose_name='Nível de Combustível')),
                ('itens_conferidos', models.TextField(blank=True, verbose_name='Itens conferidos na devolução')),
                ('avarias_novas', models.TextField(blank=True, verbose_name='Novas avarias identificadas')),
                ('documentos_apresentados', models.TextField(verbose_name='Documentos Apresentados')),
                ('assinatura_proprietario', models.BooleanField(default=False, verbose_name='Proprietário assinou')),
                ('assinatura_responsavel', models.BooleanField(default=False, verbose_name='Responsável assinou')),
                ('observacoes_gerais', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsavel_devolucao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_veiculos', to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devolucoes', to='cadastro_veiculo_apreendido.veiculoapreendido')),
            ],
            options={
                'verbose_name': 'Devolução de Veículo',
                'verbose_name_plural': 'Devoluções de Veículos',
                'ordering': ['-data_devolucao'],
            },
        ),
    ]
