# Generated by Django 6.0.4 on 2026-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_veiculo_apreendido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="veiculoapreendido",
            name="chassi",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Chassi"
            ),
        ),
    ]
