# Generated by Django 5.2.13 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_veiculo_apreendido', '0003_alter_devolucaoveiculo_id_alter_veiculoapreendido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucaoveiculo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='veiculoapreendido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
