# Generated by Django 6.0.3 on 2026-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eletronico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("COMPUTADOR", "Computador"),
                            ("NOTEBOOK", "Notebook"),
                            ("TABLET", "Tablet"),
                            ("CELULAR", "Celular"),
                            ("RADIO", "Rádio Comunicador"),
                            ("IMPRESSORA", "Impressora"),
                            ("SCANNER", "Scanner"),
                            ("CAMERA", "Câmera"),
                            ("GPS", "GPS"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "patrimonio",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="Nº Patrimônio",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nº de Série"
                    ),
                ),
                (
                    "processador",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Processador"
                    ),
                ),
                (
                    "memoria_ram",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Memória RAM"
                    ),
                ),
                (
                    "armazenamento",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Armazenamento"
                    ),
                ),
                (
                    "sistema_operacional",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WINDOWS", "Windows"),
                            ("LINUX", "Linux"),
                            ("MACOS", "MacOS"),
                            ("ANDROID", "Android"),
                            ("IOS", "iOS"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Sistema Operacional",
                    ),
                ),
                (
                    "possui_carregador",
                    models.BooleanField(
                        default=True, verbose_name="Possui Carregador?"
                    ),
                ),
                (
                    "possui_bateria",
                    models.BooleanField(default=True, verbose_name="Possui Bateria?"),
                ),
                (
                    "observacoes_acessorios",
                    models.TextField(
                        blank=True, verbose_name="Observações sobre acessórios"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em Uso"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("BAIXADO", "Baixado"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Localização"
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Eletrônico",
                "verbose_name_plural": "Eletrônicos",
                "ordering": ["tipo", "marca", "modelo"],
            },
        ),
    ]
