# Generated by Django 5.2.13 on 2026-04-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_eletronicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletronico',
            name='tipo',
            field=models.CharField(choices=[('COMPUTADOR', 'Computador'), ('NOTEBOOK', 'Notebook'), ('TABLET', 'Tablet'), ('CELULAR', 'Celular'), ('RADIO', 'Rádio Comunicador'), ('IMPRESSORA', 'Impressora'), ('SCANNER', 'Scanner'), ('CAMERA', 'Câmera'), ('GPS', 'GPS'), ('SERVIDOR', 'Servidor'), ('SWITCH', 'Switch de Rede'), ('ROTEADOR', 'Roteador'), ('MODEM', 'Modem'), ('ACCESS_POINT', 'Access Point'), ('HD_EXTERNO', 'HD Externo'), ('SSD', 'SSD'), ('PENDRIVE', 'Pendrive'), ('MONITOR', 'Monitor'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('WEBCAM', 'Webcam'), ('MICROFONE', 'Microfone'), ('HEADSET', 'Headset'), ('CAIXA_SOM', 'Caixa de Som'), ('PROJETOR', 'Projetor'), ('NOBREAK', 'Nobreak'), ('ESTABILIZADOR', 'Estabilizador'), ('SMART_TV', 'Smart TV'), ('DRONE', 'Drone'), ('VIDEO_GAME', 'Videogame'), ('LEITOR_BIOMETRICO', 'Leitor Biométrico'), ('LEITOR_CODIGO_BARRAS', 'Leitor de Código de Barras'), ('IMPRESSORA_TERMICA', 'Impressora Térmica'), ('PLOTTER', 'Plotter'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo'),
        ),
    ]
