# Generated by Django 6.0.3 on 2026-03-07 18:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro_armamentos", "0001_initial"),
        ("cadastro_equipamentos", "0001_initial"),
        ("cadastro_municoes", "0001_initial"),
        (
            "cadastro_policiais",
            "0002_alter_policial_options_remove_policial_pelotao_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cautela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_cautela",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Cautela"
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Devolução"
                    ),
                ),
                (
                    "data_prevista_devolucao",
                    models.DateTimeField(verbose_name="Previsão de Devolução"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa"),
                            ("DEVOLVIDA", "Devolvida"),
                            ("PARCIAL", "Devolução Parcial"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ATIVA",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cautelas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "devolvido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devolucoes_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Devolvido por",
                    ),
                ),
                (
                    "policial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cautelas",
                        to="cadastro_policiais.policial",
                        verbose_name="Policial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cautela",
                "verbose_name_plural": "Cautelas",
                "ordering": ["-data_cautela"],
            },
        ),
        migrations.CreateModel(
            name="ItemCautela",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_item",
                    models.CharField(
                        choices=[
                            ("ARMAMENTO_PRINCIPAL", "Armamento Principal"),
                            ("ARMAMENTO_SECUNDARIO", "Armamento Secundário"),
                            ("EQUIPAMENTO", "Equipamento"),
                            ("MUNICAO", "Munição"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Item",
                    ),
                ),
                (
                    "quantidade_municao",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Quantidade",
                    ),
                ),
                (
                    "devolvido",
                    models.BooleanField(default=False, verbose_name="Devolvido?"),
                ),
                (
                    "data_devolucao_item",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data Devolução"
                    ),
                ),
                (
                    "observacao_item",
                    models.TextField(blank=True, verbose_name="Observação do Item"),
                ),
                (
                    "armamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro_armamentos.armamento",
                        verbose_name="Armamento",
                    ),
                ),
                (
                    "cautela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="cautela_armamento.cautela",
                    ),
                ),
                (
                    "equipamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastro_equipamentos.equipamento",
                        verbose_name="Equipamento",
                    ),
                ),
                (
                    "municao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_cautela",
                        to="cadastro_municoes.municao",
                        verbose_name="Munição",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Cautela",
                "verbose_name_plural": "Itens da Cautela",
            },
        ),
    ]
