# Generated by Django 6.0.3 on 2026-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Policial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "nome_guerra",
                    models.CharField(max_length=50, verbose_name="Nome de Guerra"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("patente", models.CharField(max_length=50, verbose_name="Patente")),
                (
                    "pelotao",
                    models.CharField(blank=True, max_length=50, verbose_name="Pelotão"),
                ),
                ("telefone", models.CharField(max_length=20, verbose_name="Telefone")),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Policial",
                "verbose_name_plural": "Policiais",
            },
        ),
    ]
