# Generated by Django 6.0.3 on 2026-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_policiais", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policial",
            options={
                "ordering": ["patente", "nome_guerra"],
                "verbose_name": "Policial",
                "verbose_name_plural": "Policiais",
            },
        ),
        migrations.RemoveField(
            model_name="policial",
            name="pelotao",
        ),
        migrations.AddField(
            model_name="policial",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
        ),
        migrations.AddField(
            model_name="policial",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observações"),
        ),
        migrations.AlterField(
            model_name="policial",
            name="patente",
            field=models.CharField(
                choices=[
                    ("SD", "Soldado"),
                    ("CB", "Cabo"),
                    ("SGT", "Sargento"),
                    ("ST", "Subtenente"),
                    ("TEN", "Tenente"),
                    ("CAP", "Capitão"),
                    ("MAJ", "Major"),
                    ("TC", "Tenente Coronel"),
                    ("CEL", "Coronel"),
                ],
                max_length=20,
                verbose_name="Patente",
            ),
        ),
    ]
