# Generated by Django 6.0.3 on 2026-03-08 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastro_policiais",
            "0002_alter_policial_options_remove_policial_pelotao_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="policial",
            name="user",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="policial",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
