# Generated by Django 6.0.3 on 2026-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0003_policial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='assinatura',
            field=models.ImageField(blank=True, help_text='Upload da imagem da assinatura do policial', null=True, upload_to='assinaturas/policiais/', verbose_name='Assinatura'),
        ),
    ]
