# Generated by Django 6.0.3 on 2026-03-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0004_policial_assinatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='assinatura',
            field=models.ImageField(blank=True, help_text='Upload da imagem da assinatura do policial (formato PNG)', null=True, upload_to='assinaturas/policiais/', verbose_name='Assinatura'),
        ),
    ]
