# Generated by Django 6.0.4 on 2026-04-15 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0007_alter_policial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='barra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Barra'),
        ),
        migrations.AddField(
            model_name='policial',
            name='numero_barra',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da Barra'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='patente',
            field=models.CharField(choices=[('SD PM', 'SD PM'), ('CB PM', 'CB PM'), ('3º SGT PM', '3º SGT PM'), ('2º SGT PM', '2º SGT PM'), ('1º SGT PM', '1º SGT PM'), ('ST PM', 'ST PM'), ('2º TEN QOPM', '2º TEN QOPM'), ('1º TEN QOPM', '1º TEN QOPM'), ('CAP QOPM', 'CAP QOPM'), ('MAJ QOPM', 'MAJ QOPM'), ('TC QOPM', 'TC QOPM'), ('CEL', 'CEL')], max_length=20, verbose_name='Patente'),
        ),
    ]
