# Generated by Django 5.2.13 on 2026-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0008_policial_barra_policial_numero_barra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
