# Generated by Django 5.2.13 on 2026-04-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0009_alter_policial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='barra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Entrada'),
        ),
    ]
