# Generated by Django 5.2.13 on 2026-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0010_alter_policial_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='data_promocao',
            field=models.DateField(blank=True, help_text='Data da última promoção', null=True, verbose_name='Data da Promoção'),
        ),
    ]
