# Generated by Django 5.2.13 on 2026-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0011_policial_data_promocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policial',
            options={'ordering': ['-ordem_patente', '-barra', 'numero_barra'], 'verbose_name': 'Policial', 'verbose_name_plural': 'Policiais'},
        ),
        migrations.AddField(
            model_name='policial',
            name='ordem_patente',
            field=models.IntegerField(db_index=True, default=0, editable=False, help_text='Campo automático para ordenação hierárquica das patentes', verbose_name='Ordem da Patente'),
        ),
    ]
