# Generated by Django 5.2.13 on 2026-04-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0012_alter_policial_options_policial_ordem_patente'),
    ]

    operations = [
        migrations.AddField(
            model_name='policial',
            name='data_de_nascimento',
            field=models.DateField(blank=True, help_text='Data de nascimento', null=True, verbose_name='Data de Nascimento'),
        ),
    ]
