# Generated by Django 5.2.13 on 2026-04-20 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0013_policial_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policial',
            options={'ordering': ['-ordem_patente', 'barra', 'numero_barra'], 'verbose_name': 'Policial', 'verbose_name_plural': 'Policiais'},
        ),
    ]
