# Generated by Django 5.2.13 on 2026-04-20 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0015_alter_policial_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policial',
            options={'ordering': ['-ordem_patente', 'barra', 'numero_barra', 'data_promocao'], 'verbose_name': 'Policial', 'verbose_name_plural': 'Policiais'},
        ),
    ]
