# Generated by Django 5.2.13 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_policiais', '0017_alter_policial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
