# Generated by Django 6.0.3 on 2026-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Armamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nº de Série"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PISTOLA", "Pistola"),
                            ("REVOLVER", "Revólver"),
                            ("FUZIL", "Fuzil"),
                            ("CARABINA", "Carabina"),
                            ("ESPINGARDA", "Espingarda"),
                            ("SUBMETRALHADORA", "Submetralhadora"),
                            ("METRALHADORA", "Metralhadora"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("marca", models.CharField(max_length=50, verbose_name="Marca")),
                ("modelo", models.CharField(max_length=50, verbose_name="Modelo")),
                (
                    "calibre",
                    models.CharField(
                        choices=[
                            (".22", ".22"),
                            (".32", ".32"),
                            (".38", ".38"),
                            ("9mm", "9mm"),
                            (".40", ".40"),
                            (".45", ".45"),
                            ("12", "Calibre 12"),
                            ("5.56", "5.56mm"),
                            ("7.62", "7.62mm"),
                        ],
                        max_length=10,
                        verbose_name="Calibre",
                    ),
                ),
                (
                    "patrimonio",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Nº Patrimônio",
                    ),
                ),
                (
                    "registro",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Nº Registro"
                    ),
                ),
                (
                    "capacidade",
                    models.IntegerField(default=0, verbose_name="Capacidade (tiros)"),
                ),
                (
                    "comprimento_cano",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Comprimento do Cano (cm)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DISPONIVEL", "Disponível"),
                            ("EM_USO", "Em Uso"),
                            ("MANUTENCAO", "Em Manutenção"),
                            ("BAIXADO", "Baixado"),
                        ],
                        default="DISPONIVEL",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo?")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Armamento",
                "verbose_name_plural": "Armamentos",
                "ordering": ["tipo", "marca", "modelo"],
            },
        ),
    ]
