# Generated by Django 6.0.3 on 2026-03-15 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cadastro_policiais", "0003_policial_user"),
        ("cadastro_vtrs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EscalaGerada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_escala",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Data da Escala"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                ("texto_gerado", models.TextField(verbose_name="Texto da Escala")),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Criado por",
                    ),
                ),
                (
                    "permanencia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalas_permanencia",
                        to="cadastro_policiais.policial",
                        verbose_name="Policial na Permanência",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escala Gerada",
                "verbose_name_plural": "Escalas Geradas",
                "ordering": ["-data_escala", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Dispensa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("FOLGA", "Folga"),
                            ("LICENCA_SAUDE", "Licença Saúde"),
                            ("LUTO", "Luto"),
                            ("CASAMENTO", "Casamento"),
                            ("TREINAMENTO", "Treinamento"),
                            ("SERVICO_ADMIN", "Serviço Administrativo"),
                            ("DISPENSADO_CMD", "Dispensado pelo Cmd da Cia"),
                            ("ARMA_FOGO", "Dispensado por Arma de Fogo"),
                            ("REFORCO_POLICIAL", "Dispensado por Reforço Policial"),
                            ("OUTROS", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("24HS", "24hs"),
                            ("1_QTU", "1 QTU"),
                            ("2_QTU", "2 QTU"),
                            ("1_GIRO", "1 GIRO"),
                            ("2_GIRO", "2 GIRO"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "policial",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cadastro_policiais.policial",
                        verbose_name="Policial",
                    ),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispensas",
                        to="escala_diaria.escalagerada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispensa",
                "verbose_name_plural": "Dispensas",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Permuta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("24HS", "24hs"),
                            ("1_QTU", "1 QTU"),
                            ("2_QTU", "2 QTU"),
                            ("1_GIRO", "1 GIRO"),
                            ("2_GIRO", "2 GIRO"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permutas",
                        to="escala_diaria.escalagerada",
                    ),
                ),
                (
                    "policial_a",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permutas_como_a",
                        to="cadastro_policiais.policial",
                        verbose_name="Policial A",
                    ),
                ),
                (
                    "policial_b",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permutas_como_b",
                        to="cadastro_policiais.policial",
                        verbose_name="Policial B",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permuta",
                "verbose_name_plural": "Permutas",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="PolicialEscalaExterno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcao",
                    models.CharField(
                        choices=[
                            ("CMT_VTR", "CMT DA VTR"),
                            ("MOTORISTA", "Motorista"),
                            ("PATRULHEIRO", "Patrulheiro"),
                            ("MOTOCICLISTA", "Motociclista"),
                        ],
                        max_length=20,
                        verbose_name="Função",
                    ),
                ),
                (
                    "ordem",
                    models.IntegerField(default=0, help_text="Ordem de exibição"),
                ),
                (
                    "escala",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policiais_externos",
                        to="escala_diaria.escalagerada",
                    ),
                ),
                (
                    "policial",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cadastro_policiais.policial",
                    ),
                ),
                (
                    "viatura",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cadastro_vtrs.viatura",
                        verbose_name="Viatura",
                    ),
                ),
            ],
            options={
                "verbose_name": "Policial no Serviço Externo",
                "verbose_name_plural": "Policiais no Serviço Externo",
                "ordering": ["ordem"],
            },
        ),
    ]
