# Generated by Django 5.2.3 on 2026-04-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala_diaria", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispensa",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="escalagerada",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permuta",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="policialescalaexterno",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
