# Generated by Django 6.0.3 on 2026-04-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escala_diaria", "0002_alter_dispensa_id_alter_escalagerada_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispensa",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="escalagerada",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="permuta",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="policialescalaexterno",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
