# Generated by Django 5.2.13 on 2026-04-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala_diaria', '0004_alter_dispensa_id_alter_escalagerada_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='escalagerada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permuta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policialescalaexterno',
            name='funcao',
            field=models.CharField(choices=[('CMT_VTR', 'CMT DA VTR'), ('MOTORISTA', 'MOT'), ('PATRULHEIRO', 'PAT'), ('MOTOCICLISTA', 'MOTOCICLISTA')], max_length=20, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='policialescalaexterno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
