# Generated by Django 6.0.3 on 2026-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comandante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("patente", models.CharField(max_length=50)),
                ("data_nomeacao", models.DateField()),
                ("observacoes", models.TextField(blank=True)),
            ],
        ),
    ]
