# Generated by Django 6.0.3 on 2026-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_comandante", "0003_alter_comandante_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comandante",
            name="assinatura",
            field=models.ImageField(
                blank=True,
                help_text="Upload da imagem da assinatura do comandante (formato PNG)",
                null=True,
                upload_to="assinaturas/comandantes/",
                verbose_name="Assinatura",
            ),
        ),
        migrations.AddField(
            model_name="comandante",
            name="nome_guerra",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nome de Guerra"
            ),
        ),
        migrations.AlterField(
            model_name="comandante",
            name="patente",
            field=models.CharField(
                choices=[
                    ("SD", "Soldado"),
                    ("CB", "Cabo"),
                    ("SGT", "Sargento"),
                    ("ST", "Subtenente"),
                    ("TEN", "Tenente"),
                    ("CAP", "Capitão"),
                    ("MAJ", "Major"),
                    ("TC", "Tenente Coronel"),
                    ("CEL", "Coronel"),
                ],
                max_length=20,
            ),
        ),
    ]
