# Generated by Django 6.0.3 on 2026-04-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastro_comandante",
            "0004_comandante_assinatura_comandante_nome_guerra_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comandante",
            options={"ordering": ["-data_nomeacao"]},
        ),
        migrations.AddField(
            model_name="comandante",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
    ]
