# Generated by Django 6.0.4 on 2026-04-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro_comandante", "0005_alter_comandante_options_comandante_ativo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comandante",
            name="patente",
            field=models.CharField(
                choices=[
                    ("SD PM", "SD PM"),
                    ("CB PM", "CB PM"),
                    ("3º SGT PM", "3º SGT PM"),
                    ("2º SGT PM", "2º SGT PM"),
                    ("1º SGT PM", "1º SGT PM"),
                    ("ST PM", "ST PM"),
                    ("2º TEN QOPM", "2º TEN QOPM"),
                    ("1º TEN QOPM", "1º TEN QOPM"),
                    ("CAP QOPM", "CAP QOPM"),
                    ("MAJ QOPM", "MAJ QOPM"),
                    ("TC QOPM", "TC QOPM"),
                    ("CEL", "CEL"),
                ],
                max_length=20,
            ),
        ),
    ]
