# Generated by Django 5.2.13 on 2026-04-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_comandante', '0006_alter_comandante_patente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comandante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
