# Generated by Django 6.0.4 on 2026-04-15 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('mae', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('codigo_ocorrencia', models.CharField(max_length=255)),
                ('local', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('acusado', models.TextField(blank=True, null=True)),
                ('instrumento_usado', models.TextField(blank=True, null=True)),
                ('materiais_apreendidos', models.TextField(blank=True, null=True)),
                ('evadiu', models.BooleanField(default=False)),
                ('samu', models.BooleanField(default=False)),
                ('iml', models.BooleanField(default=False)),
                ('causa', models.TextField(blank=True, null=True)),
                ('viaturas', models.TextField(blank=True, null=True)),
                ('relato', models.TextField()),
                ('local_final', models.CharField(max_length=255)),
                ('data_final', models.DateField()),
                ('responsavel', models.CharField(max_length=255)),
                ('comunicante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicante', to='relatorio_analitico.pessoa')),
                ('testemunhas', models.ManyToManyField(blank=True, related_name='testemunhas', to='relatorio_analitico.pessoa')),
                ('vitima', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitima', to='relatorio_analitico.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Providencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providencias', to='relatorio_analitico.relatorio')),
            ],
        ),
    ]
