# Generated by Django 6.0.4 on 2026-04-15 15:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorio_analitico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumeroRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(unique=True, verbose_name='Ano')),
                ('ultimo_numero', models.IntegerField(default=0, verbose_name='Último número utilizado')),
            ],
            options={
                'verbose_name': 'Controle de Numeração',
                'verbose_name_plural': 'Controle de Numeração',
            },
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='comunicante',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='vitima',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='testemunhas',
        ),
        migrations.RemoveField(
            model_name='providencia',
            name='relatorio',
        ),
        migrations.CreateModel(
            name='RelatorioAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_relatorio', models.CharField(help_text='Número automático do relatório (ex: 001/2024)', max_length=50, verbose_name='Número do Relatório')),
                ('codigo_ocorrencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código/Tipo da ocorrência')),
                ('local', models.TextField(help_text='Endereço completo da ocorrência', verbose_name='Local')),
                ('data_ocorrencia', models.DateField(default=django.utils.timezone.now, verbose_name='Data da ocorrência')),
                ('hora_ocorrencia', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora da ocorrência')),
                ('instrumento_usado', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instrumento usado')),
                ('materiais_apreendidos', models.TextField(blank=True, help_text='Armas, veículos, drogas, objetos etc...', null=True, verbose_name='Materiais apreendidos')),
                ('evadiu_se', models.BooleanField(default=False, verbose_name='Evadiu-se do local')),
                ('samu_acionado', models.BooleanField(default=False, verbose_name='SAMU acionado')),
                ('conduzido_delegacia', models.BooleanField(default=False, verbose_name='Conduzido à Delegacia')),
                ('viaturas_guarnicoes', models.CharField(blank=True, help_text='Ex: VTR 1234 - CB Silva, SD Santos', max_length=500, null=True, verbose_name='Viaturas e guarnições envolvidas')),
                ('relato', models.TextField(help_text='Descreva detalhadamente o ocorrido', verbose_name='Relato da ocorrência')),
                ('providencias', models.TextField(help_text='Descreva as providências adotadas pela guarnição', verbose_name='Providências adotadas')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('criado_por', models.CharField(blank=True, help_text='Nome do responsável pelo relatório', max_length=100, null=True, verbose_name='Criado por')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('finalizado', 'Finalizado'), ('arquivado', 'Arquivado')], default='finalizado', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Relatório Analítico',
                'verbose_name_plural': 'Relatórios Analíticos',
                'ordering': ['-data_ocorrencia', '-criado_em'],
                'indexes': [models.Index(fields=['data_ocorrencia'], name='relatorio_a_data_oc_141a0c_idx'), models.Index(fields=['numero_relatorio'], name='relatorio_a_numero__5850b1_idx'), models.Index(fields=['status'], name='relatorio_a_status_146e24_idx')],
            },
        ),
        migrations.CreateModel(
            name='PessoaEnvolvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('acusado', 'Acusado'), ('vitima', 'Vítima'), ('testemunha', 'Testemunha')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('cpf', models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('nome_mae', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome da mãe')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas', to='relatorio_analitico.relatorioanalitico', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Pessoa Envolvida',
                'verbose_name_plural': 'Pessoas Envolvidas',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AnexoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='relatorios/anexos/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrição')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de upload')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='relatorio_analitico.relatorioanalitico', verbose_name='Relatório')),
            ],
            options={
                'verbose_name': 'Anexo do Relatório',
                'verbose_name_plural': 'Anexos dos Relatórios',
            },
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.DeleteModel(
            name='Providencia',
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
